### ISSUE TITLE
Background ANR at jdk.internal.misc.Unsafe.park

### ISSUE THREAD

**Issue by vertin** [microblink/blinkid-android#303] opened 2023-09-13 13:42 UTC
### Description

We have received several reports regarding a Background ANR issue when the host scanner activity goes to onPause state.

### Environment Details

**BlinkID version:**
6.2.0 - 6.2.2

**Device model:**
 Samsung SM-G991B, SM-N980F, SM-S901B
 Xiaomi M2103K19G

**Device Android version:**
Android 11 - Android -13

**Device ABI (processor architecture, e.g. ARMv7):**
arm64-v8a, 
armeabi-v7a, 
armeabi

### Log file
[microblink_anr.txt](https://github.com/BlinkID/blinkid-android/files/12597843/microblink_anr.txt)

Also in the report we have a potential cause, a stacktrace from a blocked thread named Camera2Control:
`at android.os.MessageQueue.next(MessageQueue.java:351)`
`   at android.os.Looper.loopOnce(Looper.java:186)`
`   at android.os.Looper.loop(Looper.java:351)`
`   at com.microblink.blinkid.secured.p3.run(unavailable:36)`

**Comment by Brankacro** [comment] 2023-09-13 15:18
Hello @vertin! Could you please provide a detailed step-by-step guide on how to reproduce the mentioned behaviour? If it is possible, it would be of great help to share a minimal code sample of the behavior so we can run it on our end.In case of any additional questions, feel free to ask. Best regards.

**Comment by vertin** [comment] 2023-09-13 15:31
@Brankacro thank you for the response.
Here is a sample implementation of our scanner activity
[Sample.txt](https://github.com/BlinkID/blinkid-android/files/12599385/Sample.txt)

Unfortunately, our team has only crash reports collected from customers' devices, and we could not find a way to reproduce the issue

**Comment by Brankacro** [comment] 2023-09-14 10:08
Thank you @vertin for providing the data.
Can you please let us know where exactly are you setting the license key? Did you follow the steps described [here](https://github.com/BlinkID/blinkid-android#-performing-your-first-scan) and set the license key before using any other classes from the SDK?
Please make sure that the license key is always set before using any method from our SDK, because .onCreate() is always called on application startup.

Also, wanted to ask you if you could set the setIntentDataTransferMode method to PERSISTED_OPTIMISED as shown [here](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-aMinimalSample/src/main/java/com/microblink/blinkid/BlinkIdSampleApp.kt#L15), and let us know how it goes.
More info about passing Recognizer objects between activities can be found on the following [link](https://github.com/BlinkID/blinkid-android#-passing-recognizer-objects-between-activities).
In case of any additional questions, feel free to reach out. Best regards.

**Comment by vertin** [comment] 2023-09-29 10:34
@Brankacro 
Have these two lines
`MicroblinkSDK.setLicenseKey(<microblink_key>, applicationContext) MicroblinkSDK.setIntentDataTransferMode(IntentDataTransferMode.PERSISTED_OPTIMISED)`
                
 right before super.onCreate() line in our ScannerActivity class, but unfortunately still struggling with the ANR from time to time

**Comment by krizaa** [comment] 2024-01-19 11:57
Hi @vertin, do you have any additional info about the ANR that could help us reproduce it?
Also, how are you implementing BlinkID in your app (integration level: https://github.com/BlinkID/blinkid-android?tab=readme-ov-file#-blinkid-sdk-integration-levels)?

**Comment by arunprasath218** [comment] 2024-02-26 05:54
I am also having this issue.. I code is based on the Custom UX sample and it follows all the recommended coding structure. Any Update regarding this ANR please. This also only affect our customer devices and only a few devices having this issue. Not All

**Comment by krizaa** [comment] 2024-03-04 10:37
Thanks for reaching out @arunprasath218. 
We managed to reproduce the issue and the fix will be released in the next version of BlinkID.

**Comment by krizaa** [comment] 2024-03-07 12:00
Will be closing this issue, if the ANR persists in the new version of BlinkID 6.6, feel free to reopen the issue.

**Closed as completed by krizaa** 2024-03-07 12:00 UTC

**Comment by arunprasath218** [comment] 2024-03-15 05:51
Hi @krizaa but BlinkID 6.6 is not yet released?

**Comment by krizaa** [comment] 2024-03-19 10:04
Sorry @arunprasath218 for my wording. It will be fixed in v6.6 which will come out this week!
